version: '2'
services:
  web:
    build: .
    ports:
     - "8080:3000"
    environment:
      - NODE_ENV=production
    volumes:
     - .:/code
    depends_on:
     - mongo
     - redis
  mongo:
    image: mongo
  redis:
    image: redis

